#ifndef THREADINGLIB_GLOBAL_H
#define THREADINGLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(THREADINGLIB_LIBRARY)
#  define THREADINGLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define THREADINGLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // THREADINGLIB_GLOBAL_H
